create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  name text not null,
  email text not null,
  phone text,
  grade text not null,
  subjects text[] not null default '{}'::text[],
  format text,
  target_date text,
  help_needed text not null,
  availability text not null,
  source_path text,
  form_version text not null,
  form_started_at_ms bigint not null,
  ip_address inet,
  user_agent text
);

create index if not exists contact_submissions_created_at_idx
  on public.contact_submissions (created_at desc);

create index if not exists contact_submissions_email_idx
  on public.contact_submissions (email);

alter table public.contact_submissions enable row level security;
