create table if not exists public.testimonial_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  parent_name text not null,
  student_grade text not null,
  student_name text,
  testimonial text not null,
  rating integer not null check (rating between 1 and 5),
  source_path text,
  form_version text not null,
  form_started_at_ms bigint not null,
  ip_address inet,
  user_agent text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  approved_at timestamptz,
  display_name text,
  display_text text
);

create index if not exists testimonial_submissions_created_at_idx
  on public.testimonial_submissions (created_at desc);

create index if not exists testimonial_submissions_status_idx
  on public.testimonial_submissions (status);

create index if not exists testimonial_submissions_parent_name_idx
  on public.testimonial_submissions (parent_name);

alter table public.testimonial_submissions enable row level security;
